### PR TITLE
Fix: Handle id site registered status

### PR DESCRIPTION
**Pull request by typerandom**
Handles the ID site `registered` result status.

Fixes #244.

### CODE REVIEW

**Comment by rdegges** [comment]
+1 the code looks perfect -- wanna fix the broken build though? Looks like there's some whitespace issue.

**Comment by robertjd** [comment]
@rdegges can you do a full UAT with our sample application to ensure that the problem is resolved?  Thanks!

**Comment by typerandom** [comment]
@rdegges Thanks man! It's fixed now. For some reason when using Sublime I sometimes insert characters that look like spaces but have some totally other character code. It has happened to me on several occasions. Quite annoying. So I need to get better at running lint right before pushing:)

**Comment by rdegges** [comment]
Working.

**Pull request merged**
