### PR TITLE
Refactor: Rename serveAngular as addSpaRoute

### PR DESCRIPTION
**Pull request by typerandom**
Small internal refactor. Simply make the use of `serveAngular()` clearer by renaming it to `addSpaRoute()`.

### CODE REVIEW

**Comment by robertjd** [comment]
This new name feels strange to me, perhaps something like "attachSpaHandler"?  FYI, this mechanism will get re-factored again when we re-visit our SPA strategy, per the new spec that Les and I worked out a few weeks ago:

https://github.com/stormpath/stormpath-framework-spec/blob/master/single-page-apps.md

**Comment by typerandom** [comment]
@robertjd Personally I feel that `addSpaRoute` is more explicit. Since "handler" for me could be anything. And I prefer `add` since it's shorter. Any specific reason it feels strange for you? The function would look like `addSpaRoute(handler)`, so for me that feels pretty descriptive.

And +1 for "SPA" spec, I look forward to when we can start implementing that :)

**Comment by timothyej** [comment]
How about `attachSpaRoute()` or `setupSpaRoute()`?

**Comment by typerandom** [comment]
@timothyej Does that add different value than `addSpaRoute`?

**Comment by timothyej** [comment]
Since we can't agree on anything at this moment, and `addSpaRoute` is still better than `serveAngular`, I'm going to merge this :+1:

**Pull request merged**
