### PR TITLE
Implement support for GitHub social login

### LINKED ISSUE #312: Implement GitHub social provider support
Implement GitHub [social provider](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#feature-description) support.

Part of #298.

### PR DESCRIPTION
**Pull request by timothyej**
Fixes #312.

This PR implements support for GitHub [social login](https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md#feature-description).

This implementation is more or less just a copy of the Google and LinkedIn implementations. I decided to not do any refactors as it will be easier to do them all together later.

I also used `exchangeAuthCodeForAccessToken()` from the LinkedIn implementation and placed it in `oauth/common.js` with some minor changes. I've not refactored LinkedIn to use this new method as that would create more review work.

### Notes

* This PR is going to be merged into `framework-spec-upgrade`.

* If at least four providers are configured, they will take up too much visual space (see the screenshot). One suggestion to fix this could be to vertically center the buttons?

* I decided to make the button darker grey as normal grey could be mistaken as *disabled* according to the SAML button discussions. Any comments?

### How to verify

1. Checkout this branch
2. Clone [express-stormpath-sample-project](https://github.com/stormpath/express-stormpath-sample-project)
3. Use `npm link` and `npm link express-stormpath` to link the library to the example project
4. Configure a GitHub Directory
5. Start your app and verify that you get the GitHub button on the login form
6. Try to login and verify that you get logged in and that the user is being created
7. See my notes above

### Screenshots

screen shot 2016-02-11 at 17 22 11

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks @timothyej !  Are you able to complete the Github login flow?  I cannot, I'm having problems with the Github API.  Please see the issue I've described in this question: http://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

While debugging this issue, I found two things that needed to be fixed and I've pushed a commit with these fixes:

* Adding the state parameter to the OAuth flow, for extra security
* We weren't handling error responses from the Github API.  You can reproduce the problem trying to re-use an authorization code on our callback url (Github will give you back a bad-token error).

On our side, this PR looks ready to merge.  But I want to know that someone can complete the entire flow first (perhaps my Github issue is somehow specific to my Github account?).

**Comment by timothyej** [comment]
Thanks for the fixes, @robertjd. Yeah, it works just fine for me. @typerandom, could you try it out?

**Comment by typerandom** [comment]
@timothyej Yeah, sure. I'm going to try it out.

**Comment by typerandom** [comment]
@timothyej I'm also seeing this error when I have `public email` set to `Don't show my email address`.

>Login failed, because we could not retrieve your email address from the provider. Please ensure that you have granted email permission to our application.

Is really the only option to allow GitHub to show the email in public? Because that doesn't sound like a good solution.

If I turn on public email, then this integration works as expected :) :+1:

**Comment by robertjd** [comment]
It turns out that the github issue is not on our side, AM will need to be modified to ask for the user's email(s) resource (see follow up in the SO question).  Let's merge this, as everything will work properly when AM is fixed.  Issue is on AM board as AM-2902

**Comment by timothyej** [comment]
Thanks @robertjd and @typerandom, I'm merging this now :+1:

**Pull request merged**
