### PR TITLE
add aupport for calling postReg and postLogin handlers (if defined) to facebok-login.js

### PR DESCRIPTION
**Pull request by DeusExLibris**
I noticed that the facebook-login,js controller did not call the postRegistrationHandler or the postLoginHandler after validating the FB token.  I copied the appropriate code from google-login.js and added it into facebook-login.js

### CODE REVIEW

**Comment by robertjd** [comment]
Thanks for this! I will review tomorrow.

**Comment by DeusExLibris** [comment]
Robert,

I noticed after a submitted the pull request that neither the Google or
Facebook login functions execute the expand-account functionality either.
Rather than spam you with a bunch of pull requests or updates, let me know
if you want the updated code and I can send it to you.

Joe

On Thu, Dec 3, 2015 at 12:36 AM, robertjd <notifications@github.com> wrote:

> Thanks for this! I will review tomorrow.
> On Dec 2, 2015 4:36 PM, "Joe Wilson" <notifications@github.com> wrote:
>
> > I noticed that the facebook-login,js controller did not call the
> > postRegistrationHandler or the postLoginHandler after validating the FB
> > token. I copied the appropriate code from google-login.js and added it
> into
> > facebook-login.js
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/stormpath/express-stormpath/pull/219
> > Commit Summary
> >
> > - add aupport for calling postRegistrationHandler(if defined) to
> > facebook-login.js
> >
> > File Changes
> >
> > - *M* lib/controllers/facebook-login.js
> > <https://github.com/stormpath/express-stormpath/pull/219/files#diff-0>
> > (15)
> >
> > Patch Links:
> >
> > - https://github.com/stormpath/express-stormpath/pull/219.patch
> > - https://github.com/stormpath/express-stormpath/pull/219.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/stormpath/express-stormpath/pull/219>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stormpath/express-stormpath/pull/219#issuecomment-161522164>
> .
>



-- 
Joe Wilson
CTO, YourCall.TV
(404) 394-9493

**Comment by robertjd** [comment]
Hi Joe, if you have the Google fix that would be great!  Just add a commit to this PR. I've reviewed what's in here for Facebook and it looks good.  Thanks for this!  When I'm ready to merge I'll push this branch to our main repo and merge from there, so that tests can run on travis.

**Comment by robertjd** [comment]
Closing in favor of #221 - so tests can run from our main repo.  Thanks again @DeusExLibris !

**Comment by DeusExLibris** [comment]
Robert,

I hate to mention this as you are in the process of merging my patch, but I
think I realized something else that needs to be put in there.  I believe
that the redirect to nextUrl in the following code should only be executed
if the request is not an API request (i.e. not POST).

Current code:

        var nextUrl = req.query.next || (resp.created ?
config.web.register.nextUri : config.web.login.nextUri);

        if (resp.created && registrationHandler) {
            registrationHandler(req.user, req, res, function () {
                res.redirect(302, nextUrl);
            });
        } else if (loginHandler) {
            loginHandler(req.user, req, res, function () {
                res.redirect(302, nextUrl);
            });
        } else {
            res.redirect(302, nextUrl);
        }

Correct code:

        var nextUrl = req.query.next || (resp.created ?
config.web.register.nextUri : config.web.login.nextUri);

        if (resp.created && registrationHandler) {
            registrationHandler(req.user, req, res, function () {
                res.redirect(302, nextUrl);
            });
        } else if (loginHandler) {
            loginHandler(req.user, req, res, function () {
                helpers.loginResponder(undefined, req.user, req, res);
            });
        } else {
            helpers.loginResponder(undefined, req.user, req, res);
        }

Otherwise, login requests wont behave the same way for social logins as
with cloud logins - that is, on POST and accepts JSON, the result would
still be to redirect.

Joe


On Fri, Dec 4, 2015 at 8:09 PM, robertjd <notifications@github.com> wrote:

> Closing in favor of #221
> <https://github.com/stormpath/express-stormpath/pull/221> - so tests can
> run from our main repo. Thanks again @DeusExLibris
> <https://github.com/DeusExLibris> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stormpath/express-stormpath/pull/219#issuecomment-162121413>
> .
>



-- 
Joe Wilson
CTO, YourCall.TV
(404) 394-9493

**Comment by robertjd** [comment]
Thanks for the heads up.  This actually shouldn't be a problem, as we use the `/login` endpoint to accept JSON-type posts for social login.  These callback handlers are only used for the page-based redirect flows, which always use GET

**Pull request closed without merging**
