### PR TITLE
guards against undefined 'application'

### PR DESCRIPTION
**Pull request by rvanegas**
Added guards against undefined "application". An undefined application occurs when node is restarted and the express-stormpath middleware is serving an API endpoint. I don't know why exactly "application" would be undefined, but the guards seem reasonable whatever the assumptions in this code may be. I include the stack traces that prompted my making these changes.

```
Cannot read property 'dataStore' of undefined
TypeError: Cannot read property 'dataStore' of undefined
    at JwtAuthenticator.authenticate (/home/ubuntu/nventi/node_modules/express-stormpath/node_modules/stormpath/lib/jwt/jwt-authenticator.js:38:32)
    at Object.module.exports [as getUser] (/home/ubuntu/nventi/node_modules/express-stormpath/lib/helpers/get-user.js:69:19)
    at stormpathMiddleware (/home/ubuntu/nventi/node_modules/express-stormpath/lib/stormpath.js:92:13)
    at Layer.handle [as handle_request] (/home/ubuntu/nventi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/nventi/node_modules/express/lib/router/index.js:312:13)
    at /home/ubuntu/nventi/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ubuntu/nventi/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ubuntu/nventi/node_modules/express/lib/router/index.js:271:10)
    at /home/ubuntu/nventi/node_modules/express/lib/router/index.js:618:15
    at next (/home/ubuntu/nventi/node_modules/express/lib/router/index.js:256:14)
```

AND

```
Cannot read property 'authenticateApiRequest' of undefined
TypeError: Cannot read property 'authenticateApiRequest' of undefined
    at Object.module.exports [as getUser] (/Users/kai/nventi/server/node_modules/express-stormpath/lib/helpers/get-user.js:186:16)
    at stormpathMiddleware (/Users/kai/nventi/server/node_modules/express-stormpath/lib/stormpath.js:92:13)
    at Layer.handle [as handle_request] (/Users/kai/nventi/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kai/nventi/server/node_modules/express/lib/router/index.js:312:13)
    at /Users/kai/nventi/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/kai/nventi/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/kai/nventi/server/node_modules/express/lib/router/index.js:271:10)
    at /Users/kai/nventi/server/node_modules/express/lib/router/index.js:618:15
    at next (/Users/kai/nventi/server/node_modules/express/lib/router/index.js:256:14)
    at cookieParser (/Users/kai/nventi/server/node_modules/cookie-parser/index.js:25:29)
```

### CODE REVIEW

**Comment by robertjd** [comment]
Hello Rodrigo!  The application would be undefined if our underlying client hasn't yet initialized itself.  Can you confirm that you are waiting for the `stormpath.ready` event before starting your Express application?  That usage looks like this:

```
var app = express();
app.use(stormpath.init(app, {
  // Optional configuration options.
  website: true
}));

// Once Stormpath has initialized itself, start your web server!
app.on('stormpath.ready', function () {
  app.listen(3000);
});
```

Disclaimer: I dislike that you have to wait for this event, I hope to get this fixed in the future.

**Comment by rvanegas** [comment]
Thanks, that does fix the issue. I didn't see any mention of stormpath.ready in the docs. Must have skimmed past it!

**Comment by rdegges** [comment]
You're totally right, btw! I've actually been planning on changing this for a while. I'm going to be spending a lot of time revamping this after the new year -- I'm currently wrapping up some work on our Node.js libraries, which should be finished soon =)

The next few things on the list:

- Make the library more magical (support all the stormpath core features).
- Change the loading strategy to be NON-LAZY (and throw better errors).

**Comment by rvanegas** [comment]
I'm glad I reached out, then!

You may be interested to know that I'm trying to integrate Stormpath with
Ember. For now, I'm using a hybrid approach, relying on Node's integration
on the server side and then somehow linking the auth to the Ember client
rendered from same server. But since Stormpath offers an Angular
integration, it would seem there's opportunity for doing this in a better
way. Maybe I can help?



--
Rodrigo Vanegas
rvanegas@gmail.com

**Comment by robertjd** [comment]
Hi @rvanegas , I missed this one but please let us know what you discover with Ember, we'd love to cooperate if possible!

**Pull request closed without merging**
