### PR TITLE
Add Facebook authorization code support

### PR DESCRIPTION
**Pull request by typerandom**
Add support for exchanging a Facebook authorization code for an access token.

#### How to verify

1. Log into the Stormpath Console and map a Facebook directory to your application.
2. Checkout [the Angular JS example project](https://github.com/stormpath/stormpath-sdk-angularjs/tree/master/example/dashboard-app). Run it and verify that you can login with Facebook. This tests authentication with an access token.
3. Go to [this React SDK PR](https://github.com/stormpath/stormpath-sdk-react/pull/46). Do steps 1-8 and step 10 (but only for the Facebook provider). This tests authentication with an authorization code.

### CODE REVIEW

**Comment by robertjd** [comment]
+1, I love this!  Verified the access token flow with the angular sample app, and the authorization code flow with the react sample app.  We should update our documentation to describe the different options, I'll make an issue to track.

**Comment by robertjd** [comment]
Oh, @typerandom I just realized something.  We need to use `stormpath.web.baseUrl` if that's configured, otherwise fallback to reading the host from the request.

**Comment by typerandom** [comment]
@robertjd Awesome!

Yeah, that makes sense. I'll fix that :)

**Comment by typerandom** [comment]
@robertjd Fixed the `config.web.baseUrl` issue.

**Comment by timothyej** [comment]
I've verified that this works with Express, Angular, and React. Well done, merging now :+1:

**Pull request merged**
